version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./financial_analytics.db
      - SECRET_KEY=your-secret-key-change-in-production
      - UPLOAD_PATH=./uploads/
      - MODEL_PATH=./models/
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=financial_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000/api/v1
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data: 